services:
  database:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      MONGO_URI: "mongodb://database:27017/myappdb"
      PORT: "4000"
    ports:
      - "4000:4000"  
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build: ./frontend
    
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  mongodb_data: